baseURL = "https://constantvigier.com/"
languageCode = "en-uk"
title = "Constant Vigier"
theme= 'choregraphy'

defaultMarkdownHandler = "blackFriday"
[blackFriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params.footer]
  content = '“Dance is a human art, performed by humans for other humans.” John Neumeier'

[params.general]
  siteTitle = 'CONSTANT VIGIER'
  home = "CHOREOGRAPHY"

[params]
  description = "Constant Vigier is a Ballet Dancer and Choregrapher"
  images = []
  title = "Constant Vigier"

[menu]

[[menu.main]]
  identifier = "home"
  name = "HOME"
  title = "HOME"
  url = "/"
  weight = -120

[[menu.main]]
  identifier = "biography"
  name = "BIOGRAPHY"
  title = "BIOGRAPHY"
  url = "/biography/"
  weight = -110

[[menu.main]]
  identifier = "creations"
  name = "CREATIONS"
  title = "Creations"
  url = "/creations/"
  weight = -100

[[menu.main]]
  identifier = "agenda"
  name = "AGENDA"
  title = "Agenda"
  url = "/agenda/"
  weight = -90

[[menu.main]]
  identifier = "contact"
  name = "CONTACT"
  title = "Contact"
  url = "/contact/"
  weight = -90

[params.assets]
  favicon = "/images/favicon.ico"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5